---
- hosts: dispacher
  become: yes
  tasks:
    - name: Create backup of resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /home/devops/resolv.conf.bak
        remote_src: yes


    - name: Modify resolv.conf nameserver
      lineinfile:
        path: /etc/resolv.conf
        regex: '^nameserver\s+'
        line: 'nameserver 8.8.8.8'


