---
- hosts: gitlab
  tasks:
    - name: copy docker compose
      become: true
      copy:
        src: /home/hex/Desktop/Docker/gitlab
        dest: /home/devops/
    - name: Deploy gitlab compose
      become: true
      docker_compose:
        project_src: /home/devops/gitlab
        state: present
