---
- hosts: harbor
  tasks:
    - name: copy docker compose file
      copy:
        src: /home/hex/Desktop/harbor
        dest: /home/devops/

    - name : execute permission for install.sh
      shell: chmod +x /home/devops/harbor/install.sh

    - name: execute permission for common.sh
      shell: chmod +x /home/devops/harbor/common.sh

    - name: execute permission for prepare
      shell: chmod +x /home/devops/harbor/prepare
  
    - name: Deploy and install harbor compose
      shell: bash /home/devops/harbor/install.sh
      
    - name: Deploy gitlab compose
      docker_compose:
        project_src: /home/devops/harbor/
        state: present

