- name: Deploy Harbor
  hosts: harbor
  become: yes
  tasks:
    - name: Copy Docker Compose file
      copy:
        src: /home/hex/Desktop/Docker/harbor
        dest: /home/devops/

    - name: Check data directory
      stat:
        path: /data
      register: data_dir
    - name: Create data directory if it doesn't exist
      file:
        path: /data
        state: directory
        mode: 0775
      when: data_dir.stat.exists == false

    - name: Set execute permission for install.sh
      file:
        path: /home/devops/harbor/install.sh
        mode: 'u+x,g+x,o+x'

    - name: Set execute permission for common.sh
      file:
        path: /home/devops/harbor/common.sh
        mode: 'u+x,g+x,o+x'

    - name: Set execute permission for prepare
      file:
        path: /home/devops/harbor/prepare
        mode: 'u+x,g+x,o+x'

    - name: Deploy and install Harbor Compose
      shell: bash /home/devops/harbor/install.sh

    - name: Deploy GitLab Compose
      docker_compose:
        project_src: /home/devops/harbor/
        state: present

