---
- hosts: all
  become: true
  tasks:
    - name: install python pip in servers
      apt:
        name: python3-pip
        state: latest
    - name: install python docker in server
      apt:
        name: python3-docker
        state: latest
