---
- hosts: all
  become: true
  tasks: 
    - name: Update server (Ubuntu)
      apt:
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    - name: upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: update server (oraclelinux)
      dnf:
        update_cache: yes
        name: httpd
        state: latest
      when: ansible_distribution == "OracleLinux"
           
