---
- hosts: all
  become: true
  tasks: 
    - name: Update server (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: update server (oraclelinux)
      dnf:
        update_cache: yes
        name: httpd
        state: latest
      when: ansible_distribution == "OracleLinux"
           
