---
- hosts: all
  become: true
  tasks: 
    - name: deploy first html file (oraclelinux)
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      
           
