---
- name: Join worker nodes to Kubernetes cluster
  hosts: masters
  become: yes
  gather_facts: yes

  tasks:
    - name: Get join token from control-plane server
      command: kubeadm token create --print-join-command
      register: join_token_output

    - name: Set join token variable
      set_fact:
        join_token: "{{ join_token_output.stdout }}"

- name: Execute join token on worker nodes
  hosts: workers
  become: yes

  tasks:
    - name: Join worker nodes to Kubernetes cluster
      shell: "{{ hostvars[groups['masters'][0]]['join_token'] }}"

